import { FormEvent, useEffect, useState } from "react";
import { Link } from "../router";
import { deleteProfileImage, getProfile, updateProfile, uploadProfileImage } from "../api";
import type { Profile } from "../types";

export function ProfilePage() {
  const [profile, setProfile] = useState<Profile | null>(null); const [status, setStatus] = useState(""); const [loadError, setLoadError] = useState(""); const [actionError, setActionError] = useState("");
  useEffect(() => { void getProfile().then(setProfile).catch((err) => setLoadError(err instanceof Error ? err.message : "Unable to load profile")); }, []);
  if (loadError) return <div className="page-empty"><h1>Unable to load profile</h1><p>{loadError}</p></div>;
  if (!profile) return <div className="loading-screen">Loading profile…</div>;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setStatus(""); setActionError(""); const data = new FormData(event.currentTarget); try { const updated = await updateProfile({ fullname: String(data.get("fullname") ?? ""), phone: String(data.get("phone") ?? ""), age: Number(data.get("age") ?? 0), weight: Number(data.get("weight") ?? 0), height: Number(data.get("height") ?? 0), gender: (String(data.get("gender") ?? "unspecified") as Profile["gender"]), specify: String(data.get("specify") ?? ""), neck_pain: Number(data.get("neck_pain") ?? 0), shoulder_pain: Number(data.get("shoulder_pain") ?? 0), elbow_pain: Number(data.get("elbow_pain") ?? 0), back_pain: Number(data.get("back_pain") ?? 0), knee_pain: Number(data.get("knee_pain") ?? 0), ankle_pain: Number(data.get("ankle_pain") ?? 0) }); setProfile(updated); setStatus("Profile saved"); } catch (err) { setActionError(err instanceof Error ? err.message : "Unable to save profile"); } };
  const upload = async (file?: File) => { if (!file) return; setStatus(""); setActionError(""); try { setProfile(await uploadProfileImage(file)); setStatus("Photo updated"); } catch (err) { setActionError(err instanceof Error ? err.message : "Unable to upload image"); } };
  const removeImage = async () => { setStatus(""); setActionError(""); try { setProfile(await deleteProfileImage()); setStatus("Photo removed"); } catch (err) { setActionError(err instanceof Error ? err.message : "Unable to remove image"); } };
  return <div className="form-page"><div className="page-title-row"><div><p className="eyebrow">Your profile</p><h1>Keep your movement context close.</h1></div><Link className="secondary-button" to="/dashboard">Back to dashboard</Link></div><form className="profile-form" onSubmit={submit}><div className="form-section profile-form-head">{profile.image_url ? <img className="profile-avatar large profile-image" src={profile.image_url} alt="Your profile" /> : <div className="profile-avatar large">{profile.name.slice(0, 1).toUpperCase()}</div>}<div><h2>{profile.name}</h2><p className="muted">{profile.email}</p><label className="upload-button">Upload profile photo<input type="file" accept="image/jpeg,image/png" onChange={(event) => void upload(event.target.files?.[0])} /></label>{profile.image_url && <button type="button" className="text-button" onClick={() => void removeImage()}>Remove photo</button>}</div></div><div className="form-grid"><label>Full name<input name="fullname" defaultValue={profile.fullname} /></label><label>Phone<input name="phone" defaultValue={profile.phone} /></label><label>Age<input name="age" type="number" min="0" max="120" defaultValue={profile.age} /></label><label>Weight (kg)<input name="weight" type="number" min="0" max="500" defaultValue={profile.weight} /></label><label>Height (cm)<input name="height" type="number" min="0" max="300" defaultValue={profile.height} /></label><label>Gender<select name="gender" defaultValue={profile.gender}><option value="unspecified">Prefer not to say</option><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option></select></label></div><div className="form-section"><h2>Pain range</h2><p className="muted">Keep these values current so your exercise choices stay relevant.</p><div className="pain-form-grid">{[["neck_pain", "Neck"], ["shoulder_pain", "Shoulder"], ["elbow_pain", "Elbow"], ["back_pain", "Back"], ["knee_pain", "Knee"], ["ankle_pain", "Ankle"]].map(([key, label]) => <label key={key}>{label}<input name={key} type="range" min="0" max="50" defaultValue={profile[key as keyof Profile] as number} /></label>)}</div></div><div className="form-section"><label>Describe your pain<textarea name="specify" defaultValue={profile.specify} maxLength={1000} rows={4} /></label></div><div className="form-actions"><span className="success-copy">{status}</span><span className="error-copy">{actionError}</span><button className="primary-button" type="submit">Save profile <span>→</span></button></div></form></div>;
}
